Updated some files...

diff --git a/.bin/jmake b/.bin/jmake
--- a/.bin/jmake
+++ b/.bin/jmake
@@ -1,10 +1,13 @@
 #!/bin/bash
 
+BUILD_ENVIRONMENT="build_environment"
+
 make_tarball=false
 sp_sync=false
 clean=false
-default_action="mvn install -Dmaven.test.skip" #don't run the regression tests
+default_action="mvn install -Dmaven.test.skip" #don't run the unit tests
 action=$default_action
+repo_toplevel="/dev/null"
 
 usage() {
   echo "Usage: jmake [-t -u -s -c]"
@@ -14,6 +17,33 @@ usage() {
   echo "  -c: clean. Ignores all other options"
   exit 0
 }
+
+isGitRepo() {
+  repo_toplevel=`git rev-parse --show-toplevel`
+
+  if [ $? != 0  ]; then
+    echo "Error: not a git repository!"
+    exit $?
+  fi
+}
+
+loadBuildEnvironment() {
+  if [ -z $MAVEN_HOME ]; then
+    if [ -f $repo_toplevel/$BUILD_ENVIRONMENT ]; then
+      . $repo_toplevel/$BUILD_ENVIRONMENT
+    else
+      echo "Could not find $BUILD_ENVIRONMENT. Bailing!!!"
+      exit 1
+    fi
+  fi
+}
+
+
+#START
+isGitRepo
+loadBuildEnvironment
+
+echo $PATH
 
 while getopts "ctush" flag
 do
@@ -27,7 +57,7 @@ do
   esac
 done
 
-rm `git rev-parse --show-toplevel`/com-yottayotta-smsv2/*.tgz
+rm $repo_toplevel/com-yottayotta-smsv2/*.tgz
 
 if [[ $make_tarball == true || $sp_sync == true || $action != $default_action ]]; then
   args=$1
@@ -73,5 +103,5 @@ if [ $? == 0 -a $sp_sync == true ]; then
   sptool -p smsv2-D*0*.tgz
 fi
 
-date
+echo "Last build at `date`"
 exit 0
diff --git a/.bin/run-cli b/.bin/run-cli
--- a/.bin/run-cli
+++ b/.bin/run-cli
@@ -1,13 +1,27 @@
 #!/bin/bash
 
+BUILD_ENVIRONMENT="build_environment"
+
+loadBuildEnvironment() {
+  if [ -z "$MAVEN_HOME" ]; then
+    if [ -f $UI_DEV_DIR/$BUILD_ENVIRONMENT ]; then
+      . $UI_DEV_DIR/$BUILD_ENVIRONMENT
+      echo "Using JAVA_HOME=$JAVA_HOME"
+    else
+      echo "Could not find $BUILD_ENVIRONMENT. Bailing!!!"
+      exit 1
+    fi
+  fi
+}
+
 isValidCLIRunDir() {
   if [ ! -e cli ]; then
     echo "Missing cli directory."
     exit -1
   fi
 
-  if [ ! -e cli/VPlexcli-init ]; then
-    echo "Missing cli/VPlexcli-init."
+  if [[ ! -e cli/VPlexcli-init && ! -e VPlexcli-init ]]; then
+    echo "Missing VPlexcli-init."
     exit -1
   fi
 
@@ -18,6 +32,7 @@ isValidCLIRunDir() {
 }
 
 isValidCLIRunDir
+loadBuildEnvironment 
 
 use_new_tarball=true
 
diff --git a/.bin/run-regresson-test b/.bin/run-regresson-test
--- a/.bin/run-regresson-test
+++ b/.bin/run-regresson-test
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+BUILD_ENVIRONMENT=$UI_DEV_DIR/build_environment
+
 isValidCLIRunDir() {
   if [ ! -e cli ]; then
      echo "Missing cli directory."
@@ -17,7 +19,25 @@ isValidCLIRunDir() {
   fi
 }
 
+loadBuildEnvironment() {
+  if [ -z "$MAVEN_HOME" ]; then
+    if [ -f $BUILD_ENVIRONMENT ]; then
+      . $BUILD_ENVIRONMENT
+      echo "Using JAVA_HOME=$JAVA_HOME"
+    else
+      echo "Could not find $BUILD_ENVIRONMENT. Bailing!!!"
+      exit 1
+    fi
+  fi
+}
+
+if [ -z "$UI_DEV_DIR" ]; then
+  echo "$UI_DEV_DIR not defined. Bailing."
+  exit -1
+fi
+
 isValidCLIRunDir
+loadBuildEnvironment
 
 TARBALL_PATH="${UI_DEV_DIR}/com-yottayotta-smsv2"
 USE_NEW_RELEASE=true
