BLA!

diff --git a/.bin/utils b/.bin/utils
--- a/.bin/utils
+++ b/.bin/utils
@@ -83,14 +83,14 @@ isNsfwRepo() {
   setGitRepoRoot
 
   if [[ ! -e $GIT_REPO_ROOT/snac ]]; then
-    echo "Error: not an nsfw repository."
+    echo "Error: not an nsfw repository!"
     exit 1
   fi
 }
 
 function die {
-  echo $*
-  exit 1
+    echo $*
+    exit 1
 }
 
 execAction() {
